server {
    # http
    #listen 80;
    #server_name localhost;

    # https
    listen 443 ssl http2;
    server_name localhost;
    ssl_certificate /home/usr/ICtools/mcp_vcs/ssl/fullchain.pem;
    ssl_certificate_key /home/usr/ICtools/mcp_vcs/ssl/privkey.pem;
    # SSL 配置
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # 日志配置
    access_log /var/log/nginx/mcp-access.log;
    error_log /var/log/nginx/mcp-error.log;


    # 特定MCP路径的配置
    location /mcp {
        proxy_pass http://localhost:8999/mcp;
        #传递原始Https信息
        #proxy_set_header Host $host;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;
        
        # 保持长连接
        proxy_set_header Connection "";
        
        # 流式传输支持
        proxy_buffering off;
        tcp_nodelay on;

        # 保持mcp-session-id header
        proxy_redirect default;
    }
    
    # 健康检查端点
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
